name: redeem
on:
  push:
    branches:
      - "main"

jobs:
  redeem:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn

      - name: Run unit tests
        run: yarn test

      - name: Install xvfb and fluxbox
        run: |
          sudo apt-get install --no-install-recommends -y \
          xvfb \
          fluxbox

      - name: Run xvfb and fluxbox
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
        env:
          DISPLAY: :0.0

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          headed: true
          command: yarn cypress:run
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
        env:
          CYPRESS_ADMIN_RPC: ${{ secrets.ADMIN_RPC }}
          CYPRESS_PUBLIC_RPC: ${{ secrets.PUBLIC_RPC }}
          NEXT_PUBLIC_TENDERLY_RPC_URL: ${{ secrets.PUBLIC_RPC }}
          DISPLAY: :0.0
